## 1. Mandatory Questions
### 1.1 Bellman Optimality Equations

Using a contraction argument, show that there exists a solution to the Bellman optimality equations. That is : show that the Bellman optimality operator is a contraction mapping. (nonlinear case)

Bellman Operators: <br /> define $T^{\pi}: \mathbb{R}^{\mathcal{S}\times{\mathcal{A}}}$ and $T^{*}: \mathbb{R}^{\mathcal{S}\times{\mathcal{A}}}$ as follows: <br />
$T^{\pi}Q(s,a) = r(s,a)+\gamma \sum_{s^{'}}\mathcal{P}(s^{'}|s,a)V_{\pi}(s^{'}) \hspace{1cm} (s,a)\in \mathcal{S}\times{\mathcal{A}}$ <br \>
$T^{*}Q(s,a) = \max_{a}\big|r(s,a)+\gamma \sum_{s^{'}}\mathcal{P}(s^{'}|s,a)V_{\pi}(s^{'})\big| \hspace{1cm} (s,a)\in \mathcal{S}\times{\mathcal{A}}$

Proof: Consider the following statement<br />
$$|\max_{z}f(z)-\max_{z}h(z)|\leq \max_{z}|f(z)-h(z)|$$
Applying this to $TV(s)$ we have:<br />
$TV_{k+1}(s)-TV_{*}(s) =\max_{a}\big|r(s,a)+\gamma\sum_{s^{'}}\mathcal{p}(s^{'}|s,a)V_k(s^{'})\big|-\max_{a}\big|r(s,a)+\gamma\sum_{s^{'}}\mathcal{p}(s^{'}|s,a)V_{*}(s^{'})\big| $ <br />
$\hspace{3.4cm} \leq \max_{a}\big|\gamma\sum_{s^{'}}\mathcal{p}(s^{'}|s,a)V_k(s^{'})-\gamma\sum_{s^{'}}\mathcal{p}(s^{'}|s,a)V_k(s^{*})\big|$<br />
$\hspace{3.4cm}\leq \max_{a}\gamma\big|\sum_{s^{'}}\mathcal{p}(s^{'}|s,a)(V_k(s^{'})-V_*(s^{'})\big|$<br />
$\hspace{3.4cm}\leq \gamma\max_{a}\big|V_k(s^{'}-V_*(s^{'})\big|$<br />
$\hspace{3.4cm}=\gamma \big|\big|V_k(s)-V_*(s^{'})\big|\big|_\infty$



Hence, $TV_{k+1}(s)-TV_{*}(s) \leq \gamma^{k}||V_0(s)-V_*(s^{'})||$, giving the geometric convergence as $0< \gamma <1$ <br />
Now we show that the nonlinear Bellman operator T is contraction mapping with respect to the maximum num.

### 1.2 Policy Iteration

Show that the values of two successive policies generated by policy iteration are nondecreasing. Assume a finite MDP and conclude (explain why) that policy iteration must terminate under a finite number of steps. Finally, show that upon termination, policy iteration must have found an optimal policy (ie. one which satisfies the optimality equations).

#### 1) Monotonicity of Bellman Operator

We need to prove $V(s)\leq V^{'}(s),\forall s\in \mathcal{S} \Rightarrow TV(s) \leq TV^{'}(s), \forall s \in \mathcal{S}$

Proof: Insert into $TV(s)$,<br />
$TV(s) = \max_{a}\big|r(s,a)+\gamma\sum_{s^{'}}\mathcal{P}(s^{'}|s,a)V(s^{'})\big|$ <br />
$\hspace{1.17cm}= r(s,a_{V}^{*})+\gamma \sum_{s^{'}}\mathcal{P}(s^{'}|s,a_{V}^{*})V(s^{'})$ <br />
$\hspace{1.17cm}\leq r(s,a_{V^{'}}^{*})+\gamma \sum_{s^{'}}\mathcal{P}(s^{'}|s,a_{V^{'}}^{*})V(s^{'})$ <br />
$\hspace{1.17cm}\leq r(s,a_{V^{'}}^{*})+\gamma \sum_{s^{'}}\mathcal{P}(s^{'}|s,a_{V^{'}}^{*})V^{'}(s^{'})$<br />
$\hspace{1.17cm} = TV^{'}(s)$

Now we show that if $V(s)\leq V^{'}(s),\forall s\in \mathcal{S}$ then $TV(s) \leq TV^{'}(s), \forall s \in \mathcal{S}$. Which means the values of twoo successive policies generated by policy iteration are nondecreasing.

#### 2) Reason of termination after a finite number of steps

when state and policy are finite, the problem becomes a deterministic shortest path problem with nonnegative arc lengths. If all cycles of the state transition graph have positive length, all policies $\pi$ that do not terminate from a state $s \in \mathcal{S}$ must satisfy $V_{\pi}(s) = \infty$, implying that there exists a final policy that terminates from all $s \in \mathcal{S}$.

#### 3) Proof of optimality

Proof: denote $V_{t}^{*} = T_{t}(V_{t+1}^{*})$, $V_{t}^{\pi} \leq T_{t}(V_{t+1}^{\pi})$, and $V_{T}^{*}=V_{T}^{\pi}$ <br />
$\hspace{2.3cm}V_{t}^{\pi} \leq T_{t}(V_{t+1}^{\pi})$ <br />
$\hspace{3.0cm}\leq T_{t}T_{t+1}(V_{t+2}^{\pi})$ <br />
$\hspace{3.0cm}$.<br />
$\hspace{3.0cm}$.<br />
$\hspace{3.0cm}$.<br />
$\hspace{3.0cm}\leq T_{t}T_{t+1}...T_{T-1}(V_{T}^{\pi})$ <br />
$\hspace{3.0cm}=T_{t}T_{t+1}...T_{T-1}(V_{T}^{*})$ <br />
$\hspace{3.0cm}=V_{t}^{*}$

Hence, any policy defined by dynamic programming is optimal.

## Track 1

Implement and compare empirically the performance of value iteration, policy iteration and modified policy iteration. Modified policy iteration is a simple variant of policy iteration in which the evaluation step is only partial.<br />
**Transition Probabilities:** <br />
P(s_0 | s_0, a_0) = 0.5, P(s_1 | s_0, a_0) = 0.5, P(s_0 | s_0, a_1) = 0, P(s_1 | s_0, a_1) = 1, P(s_1 | s_0, a_2) = 0, P(s_1 | s_1, a_2) = 1 <br />
**Rewards:** r(s_0, a_0) = 5, r(s_0, a_1) = 10, r(s_1, a_2) = -1 <br />
**discount factor:** 0.95 <br />
Also run your experiments in a second MDP of your choice (chain MDP, grid world, etc.). Explain and explore how the convergence rate of these algorithms is affected by the discount factor.

### Setting the 2-state MDP environment

In [3]:
import numpy as np
states = [0, 1]
# actions = [[0, 1], [2]]
actions = [0, 1, 2]
discount_factor = 0.95

# Transition Probabilities: P[s',s,a]  Rewards: r[s,a]
P = np.zeros([len(states), len(states), len(actions)])
R = np.zeros([len(states), len(actions)])

P[0, 0, 0] = 0.5
P[1, 0, 0] = 0.5
P[0, 0, 1] = 0
P[1, 0, 1] = 1
P[1, 0, 2] = 0
P[1, 1, 2] = 1

R[0, 0] = 5
R[0, 1] = 10
R[1, 2] = -1

### 1) Algorithm 1: Policy Iteration
### First Step: Policy Evaluation

In [15]:
def policy_eval(policy, P, R, gamma, theta=0.0001):
    """
    Args: 
        policy: |state|x|action| matrix. This is a deterministic policy for this 2-state markov decision process.
                Hence for every iteration there is a probability 1 in each row of this policy matrix.
        P: transition probability matrix. |next_state|x|state|x|action|
        R: reward matrix. |state|x|action|
        gamma: discount factor equals 0.95
        theta: repeat until delta < theta, then break
    Return:
        return value function with length of states
    """
    # Initialize Value function with all 0
    V = np.zeros(len(states))
    counter = 0
    while True:
        delta = 0
        # for each state, conduct Bellman backup
        for s in range(len(states)):
            v = 0
            for a, a_prob in enumerate(policy[s]):
                # each state has a valid action set, here we mask out unavailbale actions.
                if (s == 0 and a == 2) or (s == 1 and a == 0) or (s == 1 and a == 1):
                    continue
                # calculate value for each state
                v += sum([a_prob * P[next_s, s, a] * (R[s, a] + gamma * V[next_s]) for next_s in range(len(states))])
            # terminal condition (calculate the difference of 2 successive iterations)
            delta = max(delta, np.abs(v - V[s]))
            V[s] = v
        counter += 1
        # terminal check
        if delta < theta:
            break
    return np.array(V)

### Second Step: Policy Improvement

In [22]:
def policy_improve(policy_eval, gamma=0.95):
    """
    Args:
        policy_eval: policy evaluation function with value function returned. After every evaluation we can get the 
                     value function, then improve current policy based on value function.
        gamma: discount factor equals 0.95.
        
    Returns:
        return the optimal policy associated with the value function.
    """

    # Initialize policy matrix arbitrarily for all states
    policy = np.zeros([len(states), len(actions)], dtype=int)
    policy[0][0] = 1
    policy[1][2] = 1

    while True:
        # obtain value function of current policy
        V = policy_eval(policy, P, R, gamma=0.95)
        policy_stable = True

        for s in range(len(states)):
            
            # find the old best action
            old_a = np.argmax(policy[s])

            # policy improvement by updating the best action
            action_array = np.full(len(actions), fill_value=-np.inf)  # np.zeros(len(actions))
            for a in range(len(actions)):
                # mask out invalid situations
                if (s == 0 and a == 2) or (s == 1 and a == 0) or (s == 1 and a == 1):
                    continue
                # calculate action probability for every action and find the one with probability 1
                action_array[a] = sum(
                    P[next_s, s, a] * (R[s, a] + gamma * V[next_s]) for next_s in
                    range(len(states)))
            #update best option
            new_a = np.argmax(action_array)
            # for every 2 successive iteration, check the difference
            if new_a != old_a:
                policy_stable = False
            # save improved policy
            policy[s] = np.eye(len(actions))[new_a]
        # if our policy is stable, then stop iterating and return optimal policy with value function
        if policy_stable:
            return policy, V

In [21]:
policy, V = policy_improve(policy_eval)
print("Policy:")
print(policy)
print("")
print("Value Function:")
print(V)

Policy:
[[1 0 0]
 [0 0 1]]

Value Function:
[ -8.56957076 -19.99814218]


###  2) Algorithm 2: Value Iteration

In [36]:
def value_iteration(P, R, theta=0.0001, discount_factor=0.95):
    """
    Args:
        P: transition probability matrix. |next_state|x|state|x|action|
        R: reward matrix. |state|x|action|
        theta: 1e-4, a smaill positive threhold. Repeat until delta < theta then break
    
    Returns:
        policy: final optimal policy matrix. |state|x|action|
        V: value function
    """
    # one sweep (one update of each state)
    def one_sweep(state, V):
        """
        Args:
            state: current state s
            V: last value function input for onew sweep updating
        
        Returns:
            return the action value function used to find current best action 
        """
        action_val = np.zeros(len(actions))
        # A = np.full(len(actions), fill_value=-np.inf)
        for a in range(len(actions)):
            action_val[a] = sum([P[next_s, state, a] * (R[state, a] + discount_factor * V[next_s]) for next_s in
                        range(len(states))])
            # mask out invalid situations
            if (state == 0 and a == 2) or (state == 1 and a == 0) or (state == 1 and a == 1):
                action_val[a] = -np.inf
        return action_val
    
    # initialize value function with all 0
    V = np.zeros(len(states))
    counter = 0
    
    # repeat until delta < theta
    while True:
        counter += 1
        delta = 0
        for s in range(len(states)):
            action_val = one_sweep(s, V)           
            # check the difference between 2 successtive iteration
            delta = max(delta, np.abs(np.max(action_val) - V[s]))
            # save current best value function
            V[s] = np.max(action_val)
            
        if delta < theta:
            break
    # initialize policy with all zero
    policy = np.zeros([len(states), len(actions)])
    
    # output a deterministic policy
    for s in range(len(states)):
        
        action_val = one_sweep(s, V)
        # find the best action
        best_action = np.argmax(action_val)
        # set the policy 
        policy[s, best_action] = 1.0
        
    return policy, V

In [37]:
policy, V = value_iteration(P, R)
print("Policy: ")
print(policy)
print("")

print("Value Function:")
print(V)

Policy: 
[[ 1.  0.  0.]
 [ 0.  0.  1.]]

Value Function:
[ -8.56957076 -19.99814218]


### Algorithm 3: Modified Policy iteration
### First Step: Modified Evaluation

In [41]:
import random
def modified_evaluation(pi, P, R, U, k=20):
    for i in range(k):
        for s in range(len(states)):
            if (s == 0 and pi[s] == 2) or (s == 1 and pi[s] == 0) or (s == 1 and pi[s] == 1):
                continue
            # U[s] = R[s, pi[s]] + discount_factor * sum([P[next_s, s, pi[s]] * U[next_s] for next_s in range(len(states))])
            U[s] = sum([P[next_s, s, pi[s]] * (R[s, pi[s]] + discount_factor * U[next_s]) for next_s in range(len(states))])
    return U

### Second Step: Policy Iteration

In [42]:
def policy_iteration():
    U = dict([(s, 0) for s in states])
    pi = dict([(s, random.choice(actions)) for s in states])
    counter = 0
    while True:
        counter += 1
        U = modified_evaluation(pi, P, R, U)
        policy_stable = True
        for s in range(len(states)):
            action_array = np.full(len(actions), fill_value=-np.inf)  # np.zeros(len(actions))
            for a in range(len(actions)):

                if (s == 0 and a == 2) or (s == 1 and a == 0) or (s == 1 and a == 1):
                    continue

                action_array[a] = sum(
                    P[next_s, s, a] * (R[s, a] + discount_factor * U[next_s]) for next_s in
                    range(len(states)))

            new_a = np.argmax(action_array)

            if new_a != pi[s]:
                pi[s] = new_a
                policy_stable = False

        if policy_stable:
            return pi      #, counter

In [43]:
policy = policy_iteration()
print(policy)

{0: 0, 1: 2}


### Setting grid world MDP environment

In [47]:
UP = 0
RIGHT = 1
DOWN = 2
LEFT = 3

def gridWorld():

    shape = [4, 4]
    # define the boundary
    MAX_X = shape[0]
    MAX_Y = shape[1]

    # define the grid
    nActions = 4
    nStates = np.prod(shape)

    grid = np.arange(nStates).reshape([nActions, nActions])
    P = {}

    # https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.nditer.html
    it = np.nditer(grid, flags=['multi_index'])

    while not it.finished:
        s = it.iterindex
        y, x = it.multi_index  # y -> number of row, x -> number of column

        # initialize prob distribution
        P[s] = {a: [] for a in range(nActions)}

        # check if arrive at terminal states (position 0 and 15)
        check_terminal = lambda s: s == 0 or s == (nStates - 1)
        reward = 0.0 if check_terminal(s) else -1.0

        if check_terminal(s):
            # got terminal, next state should be itself
            P[s][UP] = [(1.0, s, reward)]
            P[s][DOWN] = [(1.0, s, reward)]
            P[s][LEFT] = [(1.0, s, reward)]
            P[s][RIGHT] = [(1.0, s, reward)]

        else:

            ns_up = s if y == 0 else s - MAX_X
            ns_right = s if x == (MAX_X - 1) else s + 1
            ns_down = s if y == (MAX_Y - 1) else s + MAX_X
            ns_left = s if x == 0 else s - 1

            P[s][UP] = [(1.0, ns_up, reward)]
            P[s][RIGHT] = [(1.0, ns_right, reward)]
            P[s][DOWN] = [(1.0, ns_down, reward)]
            P[s][LEFT] = [(1.0, ns_left, reward)]

        it.iternext()

    # Initial state distribution is uniform
    isd = np.ones(nStates) / nStates

    return nStates, nActions, P, isd

### Policy Iteration for grid world

In [48]:
def policy_evaluation(policy, P, discount_factor=0.95, theta=1e-4):
    V = np.zeros(nStates)

    while True:
        delta = 0

        for s in range(nStates):
            v = 0

            for a, a_prob in enumerate(policy[s]):

                for prob, next_s, reward in P[s][a]:
                    v += a_prob * prob * (reward + discount_factor * V[next_s])

            delta = max(delta, np.abs(v - V[s]))
            V[s] = v

        if delta < theta:
            break

    return np.array(V)


def policy_improvement(P, policy_eval_fn=policy_evaluation, discount_factor=0.95):
    policy = np.ones([nStates, nActions]) / nActions

    while True:

        V = policy_eval_fn(policy, P, discount_factor)

        policy_stable = True

        for s in range(nStates):

            old_a = np.argmax(policy[s])

            action_array = np.zeros(nActions)

            for a in range(nActions):
                for prob, next_s, reward in P[s][a]:
                    action_array[a] += prob * (reward + discount_factor * V[next_s])

            new_a = np.argmax(action_array)

            if old_a != new_a:
                policy_stable = False
            policy[s] = np.eye(nActions)[new_a]

        if policy_stable:
            return policy, V

In [49]:
nStates, nActions, P, isd = gridWorld()

policy, v = policy_improvement(P)

print("policy")
print(policy)
print("")

print("value")
print(v)
print("")

print(v.reshape([4, 4]))

policy
[[ 1.  0.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  1.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]]

value
[ 0.     -1.     -1.95   -2.8525 -1.     -1.95   -2.8525 -1.95   -1.95
 -2.8525 -1.95   -1.     -2.8525 -1.95   -1.      0.    ]

[[ 0.     -1.     -1.95   -2.8525]
 [-1.     -1.95   -2.8525 -1.95  ]
 [-1.95   -2.8525 -1.95   -1.    ]
 [-2.8525 -1.95   -1.      0.    ]]


### Value Iteration for grid world

In [50]:
def value_iteration(P, theta=0.0001, discount_factor=0.95):
    def one_sweep(state, V):
        action_val = np.zeros(nActions)
        # A = np.full(len(actions), fill_value=-np.inf)
        for a in range(nActions):
            for prob, next_s, reward in P[s][a]:
                action_val[a] = prob * (reward + discount_factor * V[next_s])
            if (state == 0 and a == 2) or (state == 1 and a == 0) or (state == 1 and a == 1):
                action_val[a] = -np.inf
        return action_val

    V = np.zeros(nStates)
    counter = 0

    while True:
        counter += 1
        delta = 0
        for s in range(nStates):
            action_val = one_sweep(s, V)
            best_action_value = np.max(action_val)
            delta = max(delta, np.abs(best_action_value - V[s]))
            V[s] = best_action_value
        if delta < theta:
            break

    policy = np.zeros([nStates, nActions])
    for s in range(nStates):
        action_val = one_sweep(s, V)
        best_action = np.argmax(action_val)

        policy[s, best_action] = 1.0
    return policy, V

In [51]:
nStates, nActions, P, isd = gridWorld()

policy, V = value_iteration(P)

print("policy")
print(policy)
print("")

print("value")
print(V)
print("")

print(V.reshape([4, 4]))

policy
[[ 1.  0.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  1.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]]

value
[ 0.     -1.     -1.95   -2.8525 -1.     -1.95   -2.8525 -1.95   -1.95
 -2.8525 -1.95   -1.     -2.8525 -1.95   -1.      0.    ]

[[ 0.     -1.     -1.95   -2.8525]
 [-1.     -1.95   -2.8525 -1.95  ]
 [-1.95   -2.8525 -1.95   -1.    ]
 [-2.8525 -1.95   -1.      0.    ]]


### Modified Policy Iteration for grid world

In [52]:
def modified_evaluation(policy, P, discount_factor=0.95, k=20):
    V = np.zeros(nStates)

    for i in range(k):

        for s in range(nStates):
            v = 0

            for a, a_prob in enumerate(policy[s]):

                for prob, next_s, reward in P[s][a]:
                    v += a_prob * prob * (reward + discount_factor * V[next_s])

            V[s] = v

    return np.array(V)


def policy_improvement(P, policy_eval_fn=policy_evaluation, discount_factor=0.95):
    policy = np.ones([nStates, nActions]) / nActions

    while True:

        V = policy_eval_fn(policy, P, discount_factor)

        policy_stable = True

        for s in range(nStates):

            old_a = np.argmax(policy[s])

            action_array = np.zeros(nActions)

            for a in range(nActions):
                for prob, next_s, reward in P[s][a]:
                    action_array[a] += prob * (reward + discount_factor * V[next_s])

            new_a = np.argmax(action_array)

            if old_a != new_a:
                policy_stable = False
            policy[s] = np.eye(nActions)[new_a]

        if policy_stable:
            return policy, V

In [54]:
nStates, nActions, P = gridWorld()

policy = policy_improvement(P)

print("policy")
print(policy)
print("")

print("value")
print(V)
print("")

print(V.reshape([4, 4]))

ValueError: too many values to unpack (expected 3)